SELECT C.COMPANY_CODE, C.FOUNDER,
                            COUNT(DISTINCT L.LEAD_MANAGER_CODE),
                            COUNT(DISTINCT S.SENIOR_MANAGER_CODE),
                            COUNT(DISTINCT M.MANAGER_CODE),
                            COUNT(DISTINCT E.EMPLOYEE_CODE)
FROM COMPANY C
    JOIN LEAD_MANAGER L ON C.COMPANY_CODE = L.COMPANY_CODE
    JOIN SENIOR_MANAGER S ON C.COMPANY_CODE = S.COMPANY_CODE
    JOIN MANAGER M ON C.COMPANY_CODE = M.COMPANY_CODE
    JOIN EMPLOYEE E ON C.COMPANY_CODE = E.COMPANY_CODE
GROUP BY C.COMPANY_CODE, C.FOUNDER