SELECT S.HACKER_ID, H.NAME
FROM SUBMISSIONS S
     JOIN CHALLENGES C ON S.CHALLENGE_ID = C.CHALLENGE_ID
     JOIN DIFFICULTY D ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
     JOIN HACKERS H ON S.HACKER_ID = H.HACKER_ID
WHERE D.SCORE = S.SCORE
GROUP BY S.HACKER_ID, H.NAME
HAVING count(S.CHALLENGE_ID) > 1
ORDER BY count(S.CHALLENGE_ID) DESC, S.HACKER_ID