SELECT H.FLAVOR
FROM FIRST_HALF H
    JOIN ICECREAM_INFO I 
    ON H.FLAVOR = I.FLAVOR
WHERE I.INGREDIENT_TYPE = 'fruit_based'
GROUP BY H.FLAVOR
HAVING SUM(H.TOTAL_ORDER) >= 3000
ORDER BY H.TOTAL_ORDER DESC;