SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_OUTS OUTS
    JOIN (SELECT *
            FROM ANIMAL_INS INS
            WHERE INS.SEX_UPON_INTAKE NOT REGEXP 'Spayed|Neutered'
         ) I ON I.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.SEX_UPON_OUTCOME REGEXP 'Spayed|Neutered'