SELECT CONCAT('/home/grep/src/', FILE.BOARD_ID, '/', FILE.FILE_ID, FILE.FILE_NAME, FILE.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE FILE
    JOIN (SELECT BOARD_ID
          FROM USED_GOODS_BOARD
          ORDER BY VIEWS DESC
          LIMIT 1) ID
          ON ID.BOARD_ID = FILE.BOARD_ID
ORDER BY FILE.FILE_ID DESC;