SELECT USER.USER_ID, USER.NICKNAME, CONCAT(USER.CITY, ' ',USER.STREET_ADDRESS1, ' ',USER.STREET_ADDRESS2) AS '전체주소', CONCAT(SUBSTRING(USER.TLNO, 1, 3),'-',SUBSTRING(USER.TLNO, 4, 4), '-', SUBSTRING(USER.TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_USER USER
    JOIN (SELECT *
         FROM USED_GOODS_BOARD
         GROUP BY WRITER_ID
         HAVING COUNT(*) >= 3) BOARD ON USER.USER_ID = BOARD.WRITER_ID
ORDER BY USER.USER_ID DESC;