SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B
    JOIN (SELECT *
            FROM BOOK_SALES
            WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1) AS BS
    ON B.BOOK_ID = BS.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY