SELECT A.AUTHOR_ID, A.AUTHOR_NAME, I.CATEGORY, SUM(I.TOTAL_SALES) AS TOTAL_SALES
FROM AUTHOR A
    JOIN (SELECT B.BOOK_ID, B.AUTHOR_ID, B.CATEGORY, S.SALES_DATE, B.PRICE * S.SALES AS TOTAL_SALES
             FROM BOOK B
             JOIN BOOK_SALES S
             ON B.BOOK_ID = S.BOOK_ID) AS I
         ON A.AUTHOR_ID = I.AUTHOR_ID
WHERE I.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, I.CATEGORY
ORDER BY A.AUTHOR_ID, I.CATEGORY DESC;