SELECT H.HISTORY_ID, ROUND((DATEDIFF(END_DATE, START_DATE) + 1) * C.DAILY_FEE * (100 - IFNULL(P.DISCOUNT_RATE, 0))/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN (SELECT *, CASE
                         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
                         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
                         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상' 
                         END AS DURATION
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) H 
          ON C.CAR_ID = H.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON H.DURATION = P.DURATION_TYPE AND C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;