SELECT INFO.INGREDIENT_TYPE AS INGREDIENT_TYPE, SUM(HALF.TOTAL_ORDER) AS TOTAL_ORDER
#  *
FROM FIRST_HALF HALF
    LEFT JOIN ICECREAM_INFO INFO ON HALF.FLAVOR	 = INFO.FLAVOR	
GROUP BY INFO.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;