SELECT I.APNT_NO, P.PT_NAME, P.PT_NO, I.MCDP_CD, I.DR_NAME, I.APNT_YMD
FROM PATIENT P
    JOIN (SELECT A.PT_NO, D.DR_NAME, D.MCDP_CD, A.APNT_NO, A.APNT_YMD
         FROM DOCTOR D
            JOIN APPOINTMENT A ON D.DR_ID = A.MDDR_ID
         WHERE A.APNT_YMD LIKE '2022-04-13%' AND A.MCDP_CD = 'CS' AND A.APNT_CNCL_YN = 'N') I
         ON P.PT_NO = I.PT_NO
ORDER BY I.APNT_YMD;